version: "3.8"

services:
  todos-db:
    image: postgres
    container_name: todos_app_db
    restart: always
    environment:
      - POSTGRES_USER=loki
      - POSTGRES_PASSWORD=dammey
      - POSTGRES_DB=todo

  app:
    container_name: todos_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todos-db:5432/todo
      - SPRING_DATASOURCE_USERNAME=loki
      - SPRING_DATASOURCE_PASSWORD=dammey
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - todos-db